// Top-level build file where you can add configuration options common to all sub-projects/modules.
//plugins {
    //alias(libs.plugins.android.application) apply false
//}
// Top‑level build file where you put plugins that every module may use.
plugins {
    // already there – generated by the template
    alias(libs.plugins.android.application) apply false

    // NEW ▶︎  Google Services Gradle plugin  (used by Firebase)
    id("com.google.gms.google-services") version "4.4.1" apply false
}

